architectury {

    common(rootProject.enabled_platforms.split(","))
}

loom{
    accessWidenerPath = project(":visor-api").file("src/main/resources/visor.accesswidener")
}

dependencies {
    compileOnly(project(':visor-api'))

    compileOnly(project(':visor-core:stubs'))

    // @Environment annotation and mixin extras
    implementation(libs.fabric.loader)

    // ---- LOCAL DEPENDENCY
    api name: 'atumvr-core-1.14.0beta-snapshot#23'
    // ----
    //api(libs.atumvr.core)

    //Other mods
    compileOnly(libs.mod.sodium)
    compileOnly(libs.mod.iris) { transitive = false }


}
